using System;
using CyrusBuilt.ControlByWeb.Events;

namespace CyrusBuilt.ControlByWeb.Daq.X320Module
{
    /// <summary>
    /// An event generated by the X-320 module. Note that this event object
    /// should be read-only by user code, so all properties contain getters
    /// only. You can use the set methods to explicitly set or override the
    /// values if necessary (such as from methods that populate the properties
    /// with values parsed from a response from the device).
    /// </summary>
    public class X320Event : EventBase
    {
        #region Fields
        private X320Action _action = X320Action.None;
        #endregion

        #region Constructors
        /// <summary>
        /// Initializes a new instance of the <b>CyrusBuilt.ControlByWeb.Daq.X320Module.X320Event</b>
        /// class. This is the default constructor.
        /// </summary>
        public X320Event()
            : base() {
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets the action applied to this event.
        /// </summary>
        public X320Action Action {
            get { return this._action; }
        }
        #endregion

        #region Methods
        /// <summary>
        /// Sets or overrides the action being applied.
        /// </summary>
        /// <param name="action">
        /// The action to apply to the relay.
        /// </param>
        public void SetOrOverrideAction(X320Action action) {
            this._action = action;
        }

        /// <summary>
        /// Resets all state values back to their defaults except for
        /// <see cref="Id"/> because the ID of the event instance should never
        /// change during the lifetime of the event unless there is need to 
        /// override the ID for some reason.
        /// </summary>
        public override void Reset() {
            base.Reset();
            this._action = X320Action.None;
        }

        /// <summary>
        /// Determines whether the specified System.Object is equal to the
        /// current instance.
        /// </summary>
        /// <param name="obj">
        /// The System.Object to compare to the current instance.
        /// </param>
        /// <returns>
        /// true if the specified System.Object is equal to the current
        /// CyrusBuilt.ControlByWeb.Daq.X320Module.X320Event; otherwise, false.
        /// </returns>
        public override Boolean Equals(Object obj) {
            // If parameter is null, then fail.
            if (obj == null) {
                return false;
            }

            // If parameter cannot be cast to X320Event, then fail.
            X320Event evt = obj as X320Event;
            if ((X320Event)evt == null) {
                return false;
            }

            // Success if the fields match.
            Boolean isMatch = ((this.Action == evt.Action) &&
                                (this.Active == evt.Active) &&
                                (this.AlwaysOn == evt.AlwaysOn) &&
                                (this.Count == evt.Count) &&
                                (this.CurrentTime == evt.CurrentTime) &&
                                (this.Id == evt.Id) &&
                                (this.IsDisabled == evt.IsDisabled) &&
                                (this.NextEvent == evt.NextEvent) &&
                                (this.Period == evt.Period) &&
                                (this.PulseDuration == evt.PulseDuration) &&
                                (this.RelayNumber == evt.RelayNumber));
            return isMatch;
        }

        /// <summary>
        /// Determines whether the specified CyrusBuilt.ControlByWeb.Daq.X320Module.X320Event
        /// is equal to the current instance.
        /// </summary>
        /// <param name="evt">
        /// The CyrusBuilt.ControlByWeb.Daq.X320Module.X320Event to compare to
        /// the current instance.
        /// </param>
        /// <returns>
        /// true if the specified CyrusBuilt.ControlByWeb.Daq.X320Module.X320Event
        /// is equal to the current CyrusBuilt.ControlByWeb.Daq.X320Module.X320Event; 
        /// otherwise, false.
        /// </returns>
        public Boolean Equals(X320Event evt) {
            // If param is null then fail.
            if ((Object)evt == null) {
                return false;
            }

            // Success if the fields match.
            Boolean isMatch = ((this.Action == evt.Action) &&
                                (this.Active == evt.Active) &&
                                (this.AlwaysOn == evt.AlwaysOn) &&
                                (this.Count == evt.Count) &&
                                (this.CurrentTime == evt.CurrentTime) &&
                                (this.Id == evt.Id) &&
                                (this.IsDisabled == evt.IsDisabled) &&
                                (this.NextEvent == evt.NextEvent) &&
                                (this.Period == evt.Period) &&
                                (this.PulseDuration == evt.PulseDuration) &&
                                (this.RelayNumber == evt.RelayNumber));
            return isMatch;
        }

        /// <summary>
        /// Returns the hash code for this instance.
        /// </summary>
        /// <returns>
        /// The hash code for this instance.
        /// </returns>
        public override Int32 GetHashCode() {
            // Since we override Equals(), we need to override GetHashCode().
            // Since the fields used to calculate the hash code are supposed to
            // be immutable, and thus never change during the life of the
            // object, we return the hashcode of the randomly generated GUID
            // that was created in the base constructor.
            return base.GetHashCode();
        }
        #endregion
    }
}
